### ISSUE TITLE
License

### ISSUE THREAD

**Issue by birdistheword96** [gold-standard-phantoms/max1726x-rs#10]
Hi,

I have seen your library and it looks really promising! I would love to try it out, maybe even contribute, but not sure if I can currently as there is no License information. Would you be able to add either a license file (ideally), or update the `cargo.toml` file with a license field?

Thanks!

**Comment by tomhampshire** [comment]
Certainly. Thanks for reminding me!
I've added the MIT license on the latest commit

**Comment by birdistheword96** [comment]
Thanks! I have a MAX17261 and I am going to try this out!
